### ISSUE TITLE
お会計が終わった後レジがリセットされていない

### ISSUE THREAD

**Issue by chiemi627** [enpitut2017/Regi-Urico-api#26]
# 状況
* お会計ボタンを押した後、個数がそのままになっている。

# コメント
* この辺はもうチームでは自明なことだろうとは思いますが一応書いておきます。
* 潰したらcloseしてくれると嬉しいです！

**Comment by urushiyama** [comment]
enpitut2017/Regi-Urico-client/pull/24 にてお会計ボタン処理の実装とともに修正されました。
