### ISSUE TITLE
APIの一覧が欲しい

### ISSUE THREAD

**Issue by urushiyama** [enpitut2017/Regi-Urico-api#39]
現状ではPull Requestのコメント探して見つけたり、ホワイトボードの画像から探したり、開発初期の頃の実装はそもそも参照するドキュメントがなかったり、と辛いので、手が空いてる人中心にAPIの一覧をまとめて欲しいです。

**Comment by shuuji3** [comment]
https://github.com/enpitut2017/Regi-Urico-api/commit/aef5f6b7bac40607c3b2ef96b780103acd871827 で`README.md`にAPIドキュメントを書きました。
