### ISSUE TITLE
GET [/events/:event_id]がユーザ認証なしで取得できてしまう

### ISSUE THREAD

**Issue by urushiyama** [enpitut2017/Regi-Urico-api#43]
[現象]
/events/:event_idにGETリクエストを送ると、そのイベントを作ったユーザ以外のトークンを指定しても、そもそもトークンを指定しなくてもイベントのアイテム一覧を取得できてしまう。

**Comment by shuuji3** [comment]
重大なバグですね…。`/items`にも同様の問題があったので、合わせて修正しました。

**Comment by urushiyama** [comment]
#45 で（エンバグしているけど：詳細は #58 ）解決。
