### ISSUE TITLE
POST [/signin]でNo Method Error

### ISSUE THREAD

**Issue by urushiyama** [enpitut2017/Regi-Urico-api#63]
POST [/signin]で存在しないアカウント名をリクエストすると、`@seller`が`nil`になるため、
`render json: {errors: @seller.errors.messages }`がNo Method Errorになる。

**Comment by shuuji3** [comment]
その場合は、`404 Not Found`を返すようにすればいいですか？

**Comment by urushiyama** [comment]
`404 Not Found`でいいかな。ただし、パスワードが間違っていた時にも同じステータスコードを返すようにしないとブルートフォースしやすくなってしまうことだけ注意。

**Comment by shuuji3** [comment]
しかし、パスワード違いの時に`Unauthorized`を返さないのは不自然な気がしませんか？ なので、もし同じステータスコードにするなら、両方`401 Unauthorized`がいいと思います。

**Comment by urushiyama** [comment]
そうですね、`401 Unauthorized`は認証フォームを表示させる意味合いもあるのでそちらの方がいいですね。
`401 Unauthorized`で統一しましょう。

**Comment by shuuji3** [comment]
OKです！ではこちらで修正しますね。

**Comment by shuuji3** [comment]
1点質問です。今はユーザー名が間違っていると
```
{
    "errors": {
        "name": [
            "is not found"
        ]
    }
}
```
が返ってきますが、パスワードが違う時には何を返しましょうか？次の2つが考えられると思います。
- ステータスコードを同じにするのと同じ理由で、パスワードが間違っていても同じようにname is not foundと返す。
- メッセージを`password does not match`のようなものにする (でもそうすると手がかりを与えてしまうことになる？)

**Comment by urushiyama** [comment]
ユーザ名が存在するかどうかを秘匿するために、全て
```json
{
    "errors": {
        "password": ["doesn't agree with name"]
    }
}
```

とするか、
```json
{
    "errors": {
        "name": ["may be incorrect"],
        "password": ["may be incorrect"]
    }
}
```

かなぁ...

**Comment by shuuji3** [comment]
`may be`って面白いね(笑) そのどちらかなら、後者かな…。

あるいは、今はブルートフォース攻撃は来ないことを前提にして、ステータスコードもエラーメッセージもそれぞれ対応するものにする？

**Comment by urushiyama** [comment]
脆弱性がわかっていて実装するのはちょっと問題があるので、`may be`の方でお願いします。

**Comment by shuuji3** [comment]
修正を行ったので #64 のWIPを外しました。確認をお願いします。
