### ISSUE TITLE
デプロイサーバーで「お会計」ボタンを押してもTwitterの認証エラーで登録できない

### ISSUE THREAD

**Issue by shuuji3** [enpitut2017/Regi-Urico-api#75]
ローカルでは正しく動作するのにサーバーでは動作していないので原因を調べています。クライアントからのリクエストは問題ありません。

<img width="448" alt="2017-12-16 18 16 39" src="https://user-images.githubusercontent.com/1425259/34069144-82aa4cc8-e28d-11e7-8a45-f13a7a9b116a.png">

<img width="354" alt="2017-12-16 18 16 51" src="https://user-images.githubusercontent.com/1425259/34069143-8283f672-e28d-11e7-8dec-24c1503ba1df.png">

**Comment by shuuji3** [comment]
`cap production deploy`でデプロイすると、上記のエラーが起こります。(環境変数変数が読み込まれていない？)

しかし、デプロイサーバーにsshして、
```bash
[deploy@enpit current]$ pwd
/home/deploy/www/Regi-Urico-api/current

[deploy@enpit current]$ env | grep -i twitter
TWITTER_ACCESS_TOKEN_SECRET=Bv4COIXsoINo2lpeZ7Fs7PN13FLCe6QtAhKJzVYiIFjkL
TWITTER_CONSUMER_KEY=mlI2XDMV9yV00k8dqqp108aJW
TWITTER_ACCESS_TOKEN=918756058226614272-WG86RImDHMoz7KxZe6vntVs177C6vgw
TWITTER_CONSUMER_SECRET=21KeXgb3MDVbnPzjz7oUdv13WFvyzdoiMQ3z095qiAd1qMpefo

[deploy@enpit current]$ bundle exec pumactl -S /home/deploy/www/Regi-Urico-api/shared/tmp/states/puma.state -F /home/deploy/www/Regi-Urico-api/shared/puma.rb start
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: production
* Listening on unix:///home/deploy/www/Regi-Urico-api/shared/tmp/sockets/puma.sock
Use Ctrl-C to stop
```
と手動でpumaを起動すると、正しく動作するようです。
```bash
[deploy@enpit current]$ bundle exec puma -C /home/deploy/www/Regi-Urico-api/shared/puma.rb --daemon
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: production
* Daemonizing...

[deploy@enpit current]$
```
でもOK。いったいなぜ…？

**Comment by kajyuuen** [comment]
ふーむ．
少し検証する必要がありますが，
- `.bashrc`に書いてある環境変数が違う
- そもそもcapistranoはbashではなくshやzsh等で実行している

という可能性がありそう

**Comment by shuuji3** [comment]
なるほど、シェルが違うという可能性には思い当たりませんでした。環境変数は `~/.bash_profile` にかかれているので、もし `bash` 以外が使われていたら読み込まれなさそうですね。 `.profile` に書けばいいのかな？

**Comment by kajyuuen** [comment]
this

**Comment by shuuji3** [comment]
まさにそのままのタイトルの記事が出てきました。これが原因っぽい！

Capistrano で.bash_profileに書いてある環境変数が読まれない件
https://qiita.com/AknEp/items/6e47ee6c363ed1ba9c68

**Comment by shuuji3** [comment]
`.bashrc` に書いたら動きました！やった〜！ 🎉
